eclipse/codewind-intellij

- README.md
Add missing build and chat badges
> Add build and chat badges

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenApplicationAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenPerformanceDashboardAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenTektonDashboardAction.java
Signed-off-by: Carl Anderson <ccc@us.ibm.com>
> Open application in external browser.

- Jenkinsfile
- dev/build.gradle
fixes https://github.com/eclipse/codewind/issues/1840
> Build and bundle two file-watcher jars into the IntelliJ plugin

- dev/src/main/java/org/eclipse/codewind/intellij/core/ProcessHelper.java
See
https://github.com/eclipse/codewind/issues/1765
https://github.com/eclipse/codewind-eclipse/pull/542
> Ensure UTF-8 encoding on strings received from cwctl

- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindConnection.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/filewatcher/CodewindIntelliJFilewatcherdConnection.java
Fixes https://github.com/eclipse/codewind/issues/983
> [983] [IntelliJ] Add file-watcher to notify backend of project changes

- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/CoreConstants.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/filetypes/CwSettingsFileType.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/filetypes/CwSettingsFileTypeDetector.java
- dev/src/main/resources/META-INF/plugin.xml
- dev/src/main/resources/messages/core/CodewindCoreBundle.properties
Fixes https://github.com/eclipse/codewind/issues/1986
See https://github.com/eclipse/codewind/issues/1986 for screen shots.
> [1986] Add .cw-settings file type

- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindSocket.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeModel.java
Have a singleton TreeModel that is used by all the Trees.
> Fix multiple views not updating correctly

- dev/src/main/java/org/eclipse/codewind/intellij/core/FileUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindConnection.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AddExistingProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AddExistingProjectForm.form
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AddExistingProjectForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.form
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindToolWindowHelper.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/AbstractBindProjectWizardStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/AddExistingProjectWizard.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/BindProjectModel.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/ConfirmProjectTypeStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/ProjectFolderStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/ProjectTypeSelectionStep.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Fixes https://github.com/eclipse/codewind/issues/981
> [981] Add existing codewind project into IntelliJ (bind)

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AddExistingProjectForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
Fixes https://github.com/eclipse/codewind/issues/2114
Signed-off-by: Keith Chong kchong@ca.ibm.com
> [2114] Get around using deprecated method; Clean up warnings

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AddExistingProjectForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
For 0.9.0 branch: Fixes https://github.com/eclipse/codewind/issues/2114 
Signed-off-by: Keith Chong kchong@ca.ibm.com
> [2114] Get around using deprecated method; Clean up warnings (0.9.0)

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/CLIUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/ProjectUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/CoreConstants.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
Fixes https://github.com/eclipse/codewind/issues/2090
> Fix appsody maven cache initialization

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/CodewindProcessTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/StartCodewindTask.java
> Remove cancel button from new project's start codewind progress monitor [0.9.0]

- dev/src/main/java/org/eclipse/codewind/intellij/core/CoreUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/OpenAppOverviewTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/toolwindow/UpdateHandler.java
> [2098] add update handler for remove and updates (0.9.0) II

- dev/src/main/java/org/eclipse/codewind/intellij/core/CoreUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/OpenAppOverviewTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/toolwindow/UpdateHandler.java
Fixes https://github.com/eclipse/codewind/issues/2098
> [2098] Remove overview page after the project is removed from Codewind

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
> [2039] "Import project” must not be at the project level (0.9.0)

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/InstallUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/ProjectUtil.java
Fixes https://github.com/eclipse/codewind/issues/2086
Signed-off-by: Keith Chong kchong@ca.ibm.com
> [2086] [IntelliJ] Increase timouts for long-running actions (0.9.0)

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
> [2039] "Import project” must not be at the project level

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/CLIUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/ProjectUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/CoreConstants.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
* Set JAVA_HOME when creating projects
* Update copyrights
* Put JAVA_HOME/bin on path for 'cwctl create'
> Fix appsody maven cache initialization [master]

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/CodewindProcessTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/StartCodewindTask.java
> Remove cancel button from new project's start codewind progress monitor [master]

- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
Fixes https://github.com/eclipse/codewind/issues/2165
> [IntelliJ] Update getting started link

- dev/build.gradle
- dev/src/main/resources/META-INF/plugin.xml
> Add change notes to plugin.xml [0.9.0]

- dev/build.gradle
- dev/src/main/resources/META-INF/plugin.xml
> Add change notes to plugin.xml [master]

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UninstallCodewindTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UpgradeCodewindTask.java
Signed-off-by: Carl Anderson <ccc@us.ibm.com>
> [2183] IntelliJ:Codewind Uninstall does not work

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
Fixes https://github.com/eclipse/codewind/issues/2198
> [2198] Change when to show the Add Existing Project action

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/InstallUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/ProjectUtil.java
Fixes https://github.com/eclipse/codewind/issues/2086 , but for master
It was already delivered to 0.9.0 via https://github.com/eclipse/codewind-intellij/pull/37
> [2086] Increase timouts for long-running actions - master

- Jenkinsfile
> Add name and description in updatePlugins.xml

- Jenkinsfile
fixes https://github.com/eclipse/codewind/issues/2201
> [master] Fix install status to display 'installed' instead of 'install' after install

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/InstallCodewindTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UninstallCodewindTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/UpgradeCodewindTask.java
> 2221 Add double click actions for install, upgrade

- dev/build.gradle
> Update plugin versioning to match updatePlugins.xml

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/InstallStatus.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/ConnectionManager.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeNodeCellRenderer.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
See https://github.com/eclipse/codewind/issues/2199
> Fix invalid error status in view

- dev/src/main/java/org/eclipse/codewind/intellij/core/CodewindApplicationFactory.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindSocket.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/JSONObjectResult.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/ProjectTemplateInfo.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/console/SocketConsole.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/CoreConstants.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/CloseAllLogsAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/ShowAllLogsAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/CloseAllLogFilesTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/OpenAppOverviewTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindToolWindowHelper.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Fixes https://github.com/eclipse/codewind/issues/989
> [989] [IntelliJ] Show project log files (Master)

- dev/src/main/java/org/eclipse/codewind/intellij/core/filetypes/CwSettingsFileTypeDetector.java
Fixes https://github.com/eclipse/codewind/issues/2168
> [2168] SVT:IntelliJ:Assertion failed: Write-action is needed

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
> Add new project menu action

- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
- dev/src/main/resources/META-INF/plugin.xml
fixes https://github.com/eclipse/codewind/issues/2300
> Fix typo in html file name

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/RemoveProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/RemoveProjectTask.java
See https://github.com/eclipse/codewind/issues/2225
> Remove multiple selected projects

- dev/src/main/java/org/eclipse/codewind/intellij/core/CoreUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/AddExistingProjectWizard.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/ConfirmProjectTypeStep.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Fixes https://github.com/eclipse/codewind/issues/2214
> [2214] Handle project validation failure in Project Bind wizard

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.form
- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/wizard/AddExistingProjectWizard.java
Fixes https://github.com/eclipse/codewind/issues/2343
@jopit , please review.  Some additional changes while testing fix for https://github.com/eclipse/codewind-intellij/pull/60
> [2343] Finish button still enabled; Misc. fixes

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/NewCodewindProjectAction.java
Fixes https://github.com/eclipse/codewind/issues/2385
> Disable New Project menu item when Codewind not running

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/DisableProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/EnableProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/TreeAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ProjectEnablementTask.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
See https://github.com/eclipse/codewind/issues/987
> Implement enable/disable project

- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
Changing link names because file names changed.
> Changing link names

- Jenkinsfile
- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
- dev/src/main/resources/META-INF/plugin.xml
fixes https://github.com/eclipse/codewind/issues/2372
> Issue #2372:  fix broken doc link for IntelliJ 0.9.0

- dev/src/main/resources/META-INF/plugin.xml
> Update changelog in plugin.xml for 0.10.0

- Jenkinsfile
For https://github.com/eclipse/codewind/issues/2378
> Pick up appsody 0.5.9

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.10.0

- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
We now have a file for adding an image registry in remote Codewind. This is a PR to update the link.
This PR relates to issue https://github.com/eclipse/codewind/issues/2382.
> Updating link to remote documentation

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeNodeCellRenderer.java
See https://github.com/eclipse/codewind/issues/2052
> Allow empty build status

- dev/src/main/resources/META-INF/plugin.xml
Updates the plugin description
https://github.com/eclipse/codewind/issues/2462
https://github.com/eclipse/codewind/issues/2462
No
The ID team has already reviewed this same description for the 0.10.0 branch in PR https://github.com/eclipse/codewind-intellij/pull/87
> Update description in plugin.xml (master)

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/NewCodewindProjectAction.java
Changes the popup menu item label from "New Project..." to "Create New Project..." for consistency with the other IDEs
https://github.com/eclipse/codewind/issues/2478
> Change popup item "New Project..." to "Create New Project..."

- dev/src/main/java/org/eclipse/codewind/intellij/core/CodewindApplication.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/CodewindIntellijApplication.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/FileUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindSocket.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/launch/CoreUiUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AbstractApplicationAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AbstractProjectDependentAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AttachDebuggerAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/RestartDebugModeAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/RestartRunModeAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/debug/CodewindConfigurationType.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/debug/CodewindDebugConfiguration.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/debug/CodewindDebugSettingsEditor.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/AttachDebuggerTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/RestartDebugModeTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/RestartRunModeTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/toolwindow/UpdateHandler.java
- dev/src/main/resources/META-INF/plugin.xml
- dev/src/main/resources/messages/core/CodewindCoreBundle.properties
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
- [X ] Enhancement
Add local debug and initial remote debug support for Codewind
https://github.com/eclipse/codewind/issues/990
More docs needed for debug support differences?
No Windows related changes, if needed
> [990] [IntelliJ] Support debugging codewind projects

- dev/src/main/java/org/eclipse/codewind/intellij/core/launch/CoreUiUtil.java
Simple null check because the component can be null.
Related to the change made to: https://github.com/eclipse/codewind/issues/2531
No
No
> [2531] Add null check

- Jenkinsfile
Bump appsody to 0.6.0
https://github.com/eclipse/codewind/issues/2557
> Bump appsody to 0.6.0

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.11.0

- dev/src/main/resources/META-INF/plugin.xml
> Update change log for 0.11.0

- dev/src/main/resources/META-INF/plugin.xml
Update change log for 0.11.0 (master)
> Update change log for 0.11.0 (master)

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AbstractProjectDependentAction.java
- [ X] Bug fix
Correct a comment to make it more generic. It was originally from RestartDebugModeTask when the actions were refactored
Want to verify https://bugs.eclipse.org/bugs/show_bug.cgi?id=560918 to see if we can merge without having a review
None opened
No
No
> Fix comment to make it generic, originally from RestartDebugModeTask

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeModel.java
- [X ] Bug fix
Fixes an exception if the new project is added last in the codewind tree
Fixes https://github.com/eclipse/codewind/issues/2578
No
No
> [2578] ArrayIndexOutOfBoundsException after creating a new project

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/ProjectTypeSelectionForm.java
Adds icons to project list in project bind wizard (Polish)
Fixes https://github.com/eclipse/codewind/issues/2100
No
See screen cap in the issue.
> [2100] Add icons to the project type list in the Bind Project wizard

- dev/build.gradle
Make plugin version match what will be in updatePlugins.xml
> Make plugin version match what will be in updatePlugins.xml

- dev/src/main/java/org/eclipse/codewind/intellij/core/connection/CodewindConnection.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AbstractApplicationAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/EnableDisableInjectMetricsAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenAppMonitorAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/EnableDisableInjectMetricsTask.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Adds Metrics Dashboard and Enable/Disable Inject App Metrics actions for the local case
Fixes https://github.com/eclipse/codewind/issues/2386
Yes - See issue for details
No
> [2386] Support for app metrics -- dashboard and injection

- .github/where-to-report-issues.md
Signed-off-by: Julie Stalley <julie_stalley@uk.ibm.com>
Adds and issue template that directs users where to raise issues.
https://github.com/eclipse/codewind/issues/2246
No
> Add an issue template here

- Jenkinsfile
- dev/build.gradle
Publish builds to archive site instead of download site
https://github.com/eclipse/codewind/issues/2700
> Publish builds to archive site instead of download site

- dev/src/main/java/org/eclipse/codewind/intellij/core/CodewindApplicationFactory.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/Logger.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/CoreConstants.java
Provide debug and trace level message support so that they can be turned on and off when needed.
https://github.com/eclipse/codewind/issues/2754
Yes
See Issue details
> [2754] Improve Logging support of IDE-specific messages

- dev/build.gradle
- dev/src/main/java/org/eclipse/codewind/intellij/core/CoreUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/KubeUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenContainerShellAction.java
- dev/src/main/resources/META-INF/plugin.xml
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Adds an action to open a shell into the running application container
https://github.com/eclipse/codewind/issues/2030
> Open Container Shell

- Jenkinsfile
Bump appsody to version 0.6.1
https://github.com/eclipse/codewind/issues/2764
No
> appsody 0.6.1

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.12.0

- dev/build.gradle
- dev/src/main/resources/META-INF/plugin.xml
Update plugin version, add change notes
> Update plugin version, add change notes

- dev/src/main/resources/META-INF/plugin.xml
Update change notes for 0.12.0
> Update change notes for 0.12.0

- README.md
> Adding period for .zip file

- dev/src/main/resources/META-INF/plugin.xml
> Update change notes for 0.13.0

- Jenkinsfile
Pickup appsody 0.6.2
For https://github.com/eclipse/codewind/issues/2995
> pickup appsody 0.6.2

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.13.0

- Jenkinsfile
Pulls in new appsody with fix https://github.com/appsody/appsody/pull/1004
Port of #135 to master
https://github.com/eclipse/codewind/issues/3113
> master: appsody 0.6.4

- dev/src/main/resources/META-INF/plugin.xml
Updates the change notes for 0.14
> Update change notes for 0.14

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.14.0

- dev/src/main/resources/META-INF/plugin.xml
> Update change notes for 0.14.1

- dev/build.gradle
- dev/src/main/resources/install-version.properties
> Update versions for 0.14.1
