- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/RemoveProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/RemoveProjectTask.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Initial drop which doesn't offer to delete the project from disk.
That will come later.
Also reorganized the context menu to match the order of items used by the Eclipse plugin.
> Add function to remove projects from Codewind

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/DisableAutoBuildAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/EnableAutoBuildAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenPerformanceDashboardAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/TreeAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/AutoBuildTask.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
See https://github.com/eclipse/codewind/issues/1974
Also fixed the order and labels of popup menu items to match Eclipse
> Add enable/disable autobuild menu item

- dev/.idea/runConfigurations/dev__latest___runIde_.xml
- dev/src/main/java/org/eclipse/codewind/intellij/core/CodewindApplication.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/Logger.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/constants/IntelliJConstants.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/InstallCodewindStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/NewCodewindProjectStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/StartCodewindStep.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/OpenIdeaProjectTask.java
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
- Run project creation in the background
- Validate input for project creation
Also, not actually related to project creation, set the file-watcher logging level to ERROR when running self-hosted in the IntelliJ IDE.  Not this is only for dev time, and does not affect the setting for the shipped plugin,
> Clean up project creation

- dev/src/main/java/org/eclipse/codewind/intellij/core/cli/InstallUtil.java
The `cwctl remove` command now takes an additional parameter `local`, see https://github.com/eclipse/codewind-installer/pull/377
> Pass 'local' to cwctl remove

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/AddExistingProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenAppOverviewAction.java
Fixes https://github.com/eclipse/codewind/issues/2274
See screenshots there.  Note other actions have to be updated too.
> [2274] Disable 'Add Existing Project' action if Codewind isn't started

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AddExistingProjectForm.java
Fixes https://github.com/eclipse/codewind/issues/2326
See screenshot with fix in the above issue.
> [2326] SVT:Browse folder dialog content is empty

- dev/src/main/resources/META-INF/plugin.xml
Removing "mdt" in the link because the file name changed.
> Fixing link to docs

- dev/src/main/java/org/eclipse/codewind/intellij/ui/constants/UIConstants.java
We now have a file for adding an image registry in remote Codewind. This is a PR to update the link.
This PR relates to issue eclipse/codewind#2382.
> Updating link to remote documentation

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
- [X ] Bug fix
Select the first log in the logs view after the user selects the `Show All` logs action for a project in the Codewind view
https://github.com/eclipse/codewind/issues/2466
No
This PR is for the 0.10.0 release / branch only.
> [2466] Select first log after running "Show All" logs

- dev/build.gradle
Strips the timestamp from the plugin version, so that it matches what will be in the updatePlugins.xml
> Make plugin version match what will be in updatePlugins.xml

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
Select the first log in the logs view after the user selects the `Show All` logs action for a project in the Codewind view.  Jag has already verified it in 0.10.0.
https://github.com/eclipse/codewind/issues/2466 but for the Master branch
No
None.  This is simply to sync up with master.  Changes to this action/task will come after the debug support PR.
> [2466] Select first log after running "Show All" logs - Master

- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/WindowToolFactory.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindToolWindowHelper.java
- [X ] Enhancement - Part of Debug Support Enhancement
Expand tree and pre-select the project in the Codewind view after the project is opened in a new window
Fixes https://github.com/eclipse/codewind/issues/2560
No
The New Project Action is a separate issue and the behavior is different.  That fix should be done in a separate PR
> [2560] Pre-select the project in the Codewind view

- dev/src/main/java/org/eclipse/codewind/intellij/core/launch/CoreUiUtil.java
- [X ] Enhancement
Still part of debug support enhancement
https://github.com/eclipse/codewind/issues/2531
No
No
> [2531] Focus switches to previous window after canceling prompt

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/NewCodewindProjectAction.java
Ensures the Codewind project type is selected in the new project wizard when the wizard is launched from the Codewind view
https://github.com/eclipse/codewind/issues/2468
No
> Select codewind module type in new project wizard

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeModel.java
- [X ] Bug fix
Fixes an exception if the new project is added last in the codewind tree for 0.11.0.  Fix has been delivered already to master.
https://github.com/eclipse/codewind/issues/2674
No
No
> [2674] ArrayIndexOutOfBoundsException when creating project [0.11.0]

- dev/build.gradle
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/SetupCodewindProjectRunnable.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindToolWindowHelper.java
- dev/src/main/resources/META-INF/plugin.xml
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
Enhancement to open the Codewind View and pre-select the project
Bug fix to fix what happens when cancel is pressed from the dialog to prompt the user to open the new project in a new window
https://github.com/eclipse/codewind/issues/2037
https://github.com/eclipse/codewind/issues/2476
and a small safe, independent change to inform the user that no logs are available (similar to the VS Code extension's behavior).  It's included here because string changes were added.
No
New plugin dependency on maven, which is in the community version
See other notes mentioned in comments in the code
For the show log file fix, a safe change was made to:
dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
and two string were …
> [2037] Open and select project tree after project creation; Cancel

- dev/src/main/java/org/eclipse/codewind/intellij/core/CoreUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/console/ILogChangeNotifier.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/console/SocketConsole.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/CodewindToolWindow.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/toolwindow/LogsViewNotifier.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindToolWindowHelper.java
- dev/src/main/resources/messages/core/CodewindCoreBundle.properties
- dev/src/main/resources/messages/ui/CodewindUIBundle.properties
- [X ] Enhancement
Add notifications 'balloons' whenever a log file has been updated but the console is not in view. This can be turned off in the preferences page.
Fixes https://github.com/eclipse/codewind/issues/2269
Yes - if we want to document how to turn off the notifications. See screencap in the issue.  We're contributing one entry into that table.
No
> [2269] Use notifications to indicate that content of a log has changed

- dev/src/main/java/org/eclipse/codewind/intellij/ui/tree/CodewindTreeNodeCellRenderer.java
Changes the content of the Codewind Connection node when an installer error occurs
Fixes https://github.com/eclipse/codewind/issues/2722
No
No
> [2722] Installer error message should not be displayed in Codewind view

- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/NewCodewindProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/NewCodewindProjectStep.java
Enables remote connection support in the New Codewind Project context menu action and the Module builder and related steps.
Fixes https://github.com/eclipse/codewind/issues/2881
No
See issue https://github.com/eclipse/codewind/issues/2881 for the scope.  There is a related enhancement to add a connections page to the wizard.
This PR should not impact the local connection behaviour.  The change simply allows for remote connections in addition to local connections.  The rest of the remote connection support will depend on this piece.
> [2881] Enable remote connections in new project menu action

- Jenkinsfile
- dev/build.gradle
- dev/src/main/java/org/eclipse/codewind/intellij/core/filetypes/CwSettingsFileTypeDetector.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/launch/CoreUiUtil.java
- dev/src/main/java/org/eclipse/codewind/intellij/core/messages/CodewindCoreBundle.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/OpenContainerShellAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/actions/RemoveProjectAction.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/messages/CodewindUIBundle.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/OpenAppOverviewTask.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/tasks/ShowAllLogFilesTask.java
- dev/src/main/resources/META-INF/plugin.xml
This requires moving up to the 2020.1.1 version of IntelliJ
Fixes the problem with opening the container shell with IntelliJ 2020.1.1
https://github.com/eclipse/codewind/issues/2952
Yes, we need to update the minimum supported level of IntelliJ
> Fix open shell in container, fix most deprecation warnings

- dev/src/main/java/org/eclipse/codewind/intellij/ui/form/AbstractCodewindDialogWrapper.java
- [X ] Enhancement
This PR adds an extensible dialog wrapper class that any Codewind for IntelliJ feature can use whenever a new dialog (not wizard) is needed to be created.  This dialog provides  OK and Cancel buttons as well as a hooked in help button (a question mark) that when clicked, will open up the browser on the URL of your choice (eg. Codewind help page).   If your dialog class instead extends DialogWrapper, the browser will open up to the IntelliJ JetBrains help.  It appears to be hardcoded.
The extender/developer simply has to implement the method 
protected abstract JComponent createCenterPanel();
to contribute the customized widget content.
Fixes https://github.com/eclipse/codewind/issues/2996
No
No
> [2996] Create extensible codewind-specific dialog wrapper

- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/CodewindModuleBuilder.java
- dev/src/main/java/org/eclipse/codewind/intellij/ui/module/SetupCodewindProjectRunnable.java
Additional change to fix an issue discovered after testing was 'unblocked'.  Needed when creating the project.  This is a must fix.   This is part of enhancement https://github.com/eclipse/codewind/issues/985
and the original PR https://github.com/eclipse/codewind-intellij/pull/137
Not specifically this change. 985, yes.
None.
> [985][2647] Manage Secure and Non-Secure Template Sources - Add'l fix
